### ISSUE TITLE
Error creating elastic search index after installing module ' elasticsearch-analysis-standardnumber'

### ISSUE THREAD

**Issue by ghost** [jprante/elasticsearch-analysis-standardnumber#2]
Hello, I installed this module on elasticsearch-analysis-standardnumber using Elasticsearch version 2.2.2 but I immediately get the following exception when performing a reindexall.

[test] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown TokenFilter type [standardnumber] for [standardnumber]];
    at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:362)
    at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:309)
    at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
    at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
    at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown TokenFilter type [standardnumber] for [standardnumber]
    at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:222)
    at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:61)
    at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
    at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
    at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
    at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
    at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:159)

**Comment by jprante** [comment]
Please use version 2.2.2.0, the plugin link is http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-standardnumber/2.2.2.0/elasticsearch-standardnumber-2.2.2.0-plugin.zip

**Comment by ghost** [comment]
Thanks jprante.
